# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: katalonTask@0
  inputs:
    version: '7.9.1'
    executeArgs: '-testSuitePath="Test Suites/Verify Operations" -executionProfile="default" -browserType="Chrome" -apiKey="c054c6b9-87df-4907-adc1-08d46d28d481" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'

